export default {
  en: {
    landingPage: {
      movie_quotes: "Movie Quotes",
      sign_up: "Sign Up",
      log_in: "Log in",
      first_line_landing: "Find any quote in",
      second_line_landing: "millions of movie lines",
      get_started: "Get started",
      interstellar: "Interstellar",
      interstellar_1: "“You have to leave something ",
      interstellar_2: "behind to go forward”",
      tenenbaums: "The Royal Tenenbaums",
      tenenbaums_1: "“I think we’re just gonna have",
      tenenbaums_2: "to be secretly in love with each other",
      tenenbaums_3: "and leave it that”",
      lotr: "The Lord of the Rings",
      lotr_1: "“It is a strange fate that we should suffer  ",
      lotr_2: "so much fear and doubt over so small a thing …",
      lotr_3: "such a little thing”",
      log_out: "Log out",
      activated: "Your account has been activated",
      go_profile: "Go to my profile",
    },
    signUp: {
      create_account: "Create an account",
      start_journey: "Start your journey!",
      name: "Name",
      email: "Email",
      password: "Password",
      password_confirmation: "Confirm password",
      name_placeholder: "At least 3 & max.15 lower case characters",
      email_placeholder: "Enter your email",
      password_placeholder: "At least 8 & max.15 lower case characters",
      password_confirmation_placeholder: "Confirm password",
      google_sign: "Sign Up with Google",
      have_account: "Already have an account?",
      check_email:
        "Please check your email and follow the instructions to activate your account.",
      thank_you: "Thank you!",
      go_to_my_email: "Go to my email",
    },
    logIn: {
      log_in: "Log in to your account",
      welcome: "Welcome back! Please enter your details",
      remember: "Rememer me",
      forgot_password: "Forgot password",
      sign_in: "Sign in",
      google_log: "Sign in with Google",
      password_placeholder: "Password",
      dont_have_acc: "Don't have an account?",
      sign_up: "Sign up",
      close: "Close",
      send_instructions: "Send instructions",
      forgot_instuction:
        "Enter the email and we’ll send an email with instructions to reset your password",
      back_to_login: "Back to log in",
      create_password: "Create new password",
      create_description:
        "Your new password must be different from previous used passwords",
      reset_password: "Reset password",
      check_email: "Check your email",
      check_pass_des:
        "We have sent a password recover instructions to your email",
      success: "Success!",
      success_des: "Your Password changed successfully",
      go_newsfeed: "Go to my newsfeed",
      error: "Field must contain only lower case characters",
    },
    personalDash: {
      newsfeed: "Newsfeed",
      list_of_movies: "List of movies",
      edit_profile: "Edit your profile",
    },
    newQuote: {
      write_new: "Write new quote",
      drag: "Drag & drop your image here or ",
      choose: "Choose File",
      choose_movie: "Choose movie",
      post: "Post",
      upload: "Upload image",
    },
    movieList: {
      my_list: "My list of movies",
      total: "Total",
      search: "Search",
      add_movie: "Add movie",
    },
    singleMovie: {
      movie_description: "Movie description",
      quotes: "Quotes",
      total: "total",
      add_quote: "Add quote",
      director: "Director:",
      edit: "Edit movie",
      planning: "Planing to delete movie?",
      des: "Remember that all quotes to a film will be gone too",
      delete: "Delete movie",
      cancel: "Cancel",
    },
    quoteMenu: {
      edit: "Edit",
      delete: "Delete",
      view: "View",
    },
    addQuote: {
      quote_en: "Quote in English",
      view: "View quote",
      edit: "Edit quote",
      save: "Save changes",
    },
    profilePage: {
      username: "Username",
      email: "Email",
      secondary: "Secondary email",
      edit: "Edit",
      primary: "Primary",
      make_primary: "Make primary",
      remove: "Remove",
      add_new_email: "Add new email",
      password: "Password",
      are_you_sure: "Are you sure to make changes?",
      add: "Add",
      cancel: "Cancel",
      save: "Save changes",
      upload: "Upload new photo",
      unverified: "Not verified",
      pass_should: "Password should contain:",
      eight: "8 or more characters",
      fifteen: "15 lowercase characters",
      new_pass: "New Password",
      confirm_new_pass: "Confirm new password",
      new_username: "Enter new username",
      verify_new_email: "Please verify new email",
      new_email: "New email",
      password_changed: "Password changed successfully",
      username_changed: "Username changed successfully",
      change_primary: "Change primary email",
      thank_you: "Thank you!",
      new_email_verified: "New email has been verified",
      go_back: "Go Back",
    },
    searchBar: {
      enter: "Enter",
      movies: "to search movies",
      quotes: "to search quotes",
      search: "Search",
    },
    eachComment: {
      new_comment: "Write new comment",
    },
    addMovie: {
      add: "Add movie",
      genre: "Genre",
      year: "Year",
    },
    notificationBar: {
      notifications: "Notifications",
      mark: "Mark all as read",
      commented: "Commented on your movie quote",
      liked: "Liked your movie quote",
      new: "New",
    },
    notFound: {
      woops: "Whoops!",
      cant: "We can't see the page you are looking for",
      home: "Return home",
    },
    shallNot: {
      shall_not: "You shall not pass!",
      sorry: "Sorry, but you don’t have permission to access this page",
      home: "Return home",
    },
  },
};
