export default {
  ka: {
    landingPage: {
      movie_quotes: "ციტატები ფილმებიდან",
      sign_up: "რეგისტრაცია",
      log_in: "შესვლა",
      first_line_landing: "იპოვე ნებისმიერი ციტატა",
      second_line_landing: "მილიონობით ფილმიდან",
      get_started: "დაიწყე",
      interstellar: "ინტერსტელარი",
      interstellar_1: "“წინ წასასვლელად, რაღაცას ",
      interstellar_2: "უკან ვიტოვებთ”",
      tenenbaums: "ტენენბაუმების ოჯახი",
      tenenbaums_1: "“მგონი, ჩვენი სიყვარული საიდუმლოდ",
      tenenbaums_2: "უნდა დარჩეს და ამას მეტჯერ",
      tenenbaums_3: "აღარ მივუბრუნდეთ”",
      lotr: "ბეჭდების მბრძანებელი",
      lotr_1: "“ძალიან უცნაურია, რომ ჩვენ უნდა ვიტანჯოთ,  ",
      lotr_2: "ამდენი უნდა ვიტანჯოთ და საფრთხეში ვიყოთ …",
      lotr_3: "ასეთი პატარა ნივთის გამო”",
      log_out: "გასვლა",
      activated: "თქვენი ანგარიში აქტიურია",
      go_profile: "შესვლა",
    },
    signUp: {
      create_account: "შექმენი ანგარიში",
      start_journey: "დაიწყე მოგზაურობა!",
      name: "სახელი",
      email: "მეილი",
      password: "პაროლი",
      password_confirmation: "პაროლი განმეორებით",
      name_placeholder: "მინ.3 და მაქს.15 ქვ. რეგისტრის სიმბოლო",
      email_placeholder: "შეიყვანეთ თქვენი მეილი",
      password_placeholder: "მინ.8 და მაქს.15 ქვ. რეგისტრის სიმბოლო",
      password_confirmation_placeholder: "გაიმეორეთ პაროლი",
      google_sign: "დაიწყე Google–ის ანგარიშით",
      have_account: "უკვე გაქვს ანგარიში?",
      check_email:
        "შეამოწმეთ მეილი და მიყევით ინსტრუქციას თქვენი ანგარიშის გასააქტიურებლად.",
      thank_you: "მადლობა!",
      go_to_my_email: "მეილი",
    },
    logIn: {
      log_in: "შედით თქვენს ანგარიშზე",
      welcome: "კეთილი დაბრუნება! შეიყვანეთ მონაცემები",
      remember: "დაიმახსოვრე",
      forgot_password: "პაროლი დამავიწყდა",
      sign_in: "შესვლა",
      google_log: "შესვლა Google-ის ანგარიშით",
      password_placeholder: "პაროლი",
      dont_have_acc: "არ გაქვს ანგარიში?",
      sign_up: "დარეგისტრირდი",
      close: "დახურვა",
      send_instructions: "ინსტრუქციის მიღება",
      forgot_instuction:
        "შეიყვანე მეილი, ჩვენ კი სანაცვლოდ პაროლის აღდგენის ინსტრუქციას გამოგიგზავნით",
      back_to_login: "უკან დაბრუნება",
      create_password: "შექმენი ახალი პაროლი",
      create_description:
        "თქვენი ახალი პაროლი უნდა განსხვავდებოდეს თქვენი ძველი პაროლისაგან",
      reset_password: "ცვლილების შენახვა",
      check_email: "შეამოწმეთ მეილი",
      check_pass_des: "მეილზე გამოგიგზავნეთ ინტრუქციები პაროლის აღსადგენად",
      success: "წარმატებით განახლდა!",
      success_des: "თქვენ წარმატებით შეცვალეთ პაროლი",
      go_newsfeed: "გვერდზე შესვლა",
      error: "უნდა შედგებოდეს პატარა ასოებისგან",
    },
    personalDash: {
      newsfeed: "ნიუსფიდი",
      list_of_movies: "ჩემი ფილმები",
      edit_profile: "პროფილის რედაქტირება",
    },
    newQuote: {
      write_new: "დაამატე ციტატა",
      drag: "გადმოიტანე სურათი ან ",
      choose: "აირჩიე",
      choose_movie: "აირჩიე ფილმი",
      post: "დაამატე",
      upload: "ატვირთე სურათი",
    },
    movieList: {
      my_list: "ჩემი ფილმების სია",
      total: "ჯამში",
      search: "ძებნა",
      add_movie: "დაამატე ფილმი",
    },
    singleMovie: {
      movie_description: "ფილმის აღწერა",
      quotes: "ციტატები",
      total: "ჯამში",
      add_quote: "დაამატე ციტატა",
      director: "რეჟისორი:",
      edit: "ფილმის რედაქტირება",
      planning: "ფილმის წაშლას აპირებ?",
      des: "გახსოვდეს, მასთან ერთად არსებული ფილმის ციტატებიც წაიშლება",
      delete: "წაშლა",
      cancel: "გაუქმება",
    },
    quoteMenu: {
      edit: "რედაქტირება",
      delete: "წაშლა",
      view: "ნახვა",
    },
    addQuote: {
      view: "ციტატის ნახვა",
      edit: "რედაქტირება",
      save: "ცვლილების შენახვა",
    },
    profilePage: {
      username: "სახელი",
      email: "მეილი",
      secondary: "დამატებითი მეილი",
      edit: "რედაქტირება",
      primary: "მთავარი",
      make_primary: "გახადე მთავარი",
      remove: "ამოღება",
      add_new_email: "დაამატე მეილი",
      password: "პაროლი",
      are_you_sure: "დარწმუნებული ხარ ცვლილელებში?",
      add: "დამატება",
      cancel: "გაუქმება",
      save: "შენახვა",
      upload: "ატვირთე ახალი სურათი",
      unverified: "არააქტიური",
      pass_should: "პაროლი უნდა შეიცავდეს:",
      eight: "8 ან მეტ სიმბოლოს",
      fifteen: "15 პატარა ასოს",
      new_pass: "ახალი პაროლი",
      confirm_new_pass: "გაიმეორე ახალი პაროლი",
      new_username: "შეიყვანე ახალი სახელი",
      verify_new_email: "გთხოვთ დაავერიფიციროთ ახალი მეილი",
      new_email: "ახალი მეილი",
      password_changed: "პაროლი წარმატებით შეიცვალა",
      username_changed: "სახელი წარმატებით შეიცვალა",
      change_primary: "შეცვალე მთავარი მეილი",
      thank_you: "Thank you!",
      new_email_verified: "New email has been verified",
      go_back: "Go Back",
    },
    searchBar: {
      enter: "შეიყვანე",
      movies: "ფილმების მოსაძებნად",
      quotes: "ციტატების მოსაძებნად",
      search: "მოძებნე",
    },
    eachComment: {
      new_comment: "დაამატე კომენტარი",
    },
    addMovie: {
      add: "დაამატე ფილმი",
      genre: "ჟანრი",
      year: "წელი",
    },
    notificationBar: {
      notifications: "შეტყობინებები",
      mark: "ყველას წაკითხვა",
      commented: "დააკომენტარა შენს ციტატაზე",
      liked: "მოეწონა შენი ციტატა",
      new: "ახალი",
    },
    notFound: {
      woops: "უუუპს!",
      cant: "ჩვენ ვერ ვიპოვეთ გვერდი რომელსაც ეძებ",
      home: "დაბრუნება",
    },
    shallNot: {
      shall_not: "შენ ვერ გაივლი!",
      sorry: "მაპატიე, მაგრამ შენ არ გაქვს შესაბამისი უფლებები აქ ვიზიტისთივს",
      home: "დაბრუნება",
    },
  },
};
